import { assertEquals } from "./deps.ts";

import SimpleGameData from "../src/SimpleGameData.ts";
import RawGameRecordExample from "./helpers/RawGameRecordExample.ts";

Deno.test("SimpleGameData example", () => {
  const raw = RawGameRecordExample();
  const simpleGameData = SimpleGameData(raw);

  assertEquals(simpleGameData, {
    name: "Friendly Match",
    width: 13,
    height: 13,
    externalId: "ogs:game:28073181",
    ranked: true,
    komi: 0.5,
    players: {
      black: {
        externalId: "ogs:player:630242",
        username: "voltrevo",
        rank: 22.77358926085324,
      },
      white: {
        externalId: "ogs:player:496781",
        username: "Play like DD",
        rank: 17.48806770555165,
      },
    },
    outcome: { winner: "black", detail: { type: "score", lead: 30.5 } },
    moves: [
      { pos: { x: 10, y: 4 }, color: "white" },
      { pos: { x: 4, y: 11 }, color: "black" },
      { pos: { x: 9, y: 11 }, color: "white" },
      { pos: { x: 10, y: 10 }, color: "black" },
      { pos: { x: 10, y: 11 }, color: "white" },
      { pos: { x: 11, y: 11 }, color: "black" },
      { pos: { x: 11, y: 12 }, color: "white" },
      { pos: { x: 11, y: 10 }, color: "black" },
      { pos: { x: 12, y: 12 }, color: "white" },
      { pos: { x: 12, y: 11 }, color: "black" },
      { pos: { x: 10, y: 9 }, color: "white" },
      { pos: { x: 9, y: 10 }, color: "black" },
      { pos: { x: 9, y: 9 }, color: "white" },
      { pos: { x: 8, y: 10 }, color: "black" },
      { pos: { x: 8, y: 11 }, color: "white" },
      { pos: { x: 10, y: 8 }, color: "black" },
      { pos: { x: 11, y: 9 }, color: "white" },
      { pos: { x: 11, y: 8 }, color: "black" },
      { pos: { x: 9, y: 8 }, color: "white" },
      { pos: { x: 12, y: 9 }, color: "black" },
      { pos: { x: 9, y: 7 }, color: "white" },
      { pos: { x: 9, y: 3 }, color: "black" },
      { pos: { x: 10, y: 3 }, color: "white" },
      { pos: { x: 9, y: 4 }, color: "black" },
      { pos: { x: 9, y: 5 }, color: "white" },
      { pos: { x: 10, y: 6 }, color: "black" },
      { pos: { x: 10, y: 7 }, color: "white" },
      { pos: { x: 11, y: 7 }, color: "black" },
      { pos: { x: 9, y: 6 }, color: "white" },
      { pos: { x: 10, y: 5 }, color: "black" },
      { pos: { x: 11, y: 4 }, color: "white" },
      { pos: { x: 11, y: 5 }, color: "black" },
      { pos: { x: 12, y: 6 }, color: "white" },
      { pos: { x: 11, y: 6 }, color: "black" },
      { pos: { x: 12, y: 5 }, color: "white" },
      { pos: { x: 12, y: 8 }, color: "black" },
      { pos: { x: 12, y: 7 }, color: "white" },
      { pos: { x: 10, y: 2 }, color: "black" },
      { pos: { x: 11, y: 2 }, color: "white" },
      { pos: { x: 11, y: 1 }, color: "black" },
      { pos: { x: 9, y: 2 }, color: "white" },
      { pos: { x: 10, y: 1 }, color: "black" },
      { pos: { x: 9, y: 1 }, color: "white" },
      { pos: { x: 12, y: 4 }, color: "black" },
      { pos: { x: 12, y: 3 }, color: "white" },
      { pos: { x: 11, y: 3 }, color: "black" },
      { pos: { x: 7, y: 10 }, color: "white" },
      { pos: { x: 8, y: 2 }, color: "black" },
      { pos: { x: 8, y: 9 }, color: "white" },
      { pos: { x: 7, y: 6 }, color: "black" },
      { pos: { x: 7, y: 7 }, color: "white" },
      { pos: { x: 6, y: 7 }, color: "black" },
      { pos: { x: 7, y: 8 }, color: "white" },
      { pos: { x: 6, y: 8 }, color: "black" },
      { pos: { x: 6, y: 9 }, color: "white" },
      { pos: { x: 5, y: 10 }, color: "black" },
      { pos: { x: 6, y: 11 }, color: "white" },
      { pos: { x: 6, y: 10 }, color: "black" },
      { pos: { x: 5, y: 11 }, color: "white" },
      { pos: { x: 5, y: 9 }, color: "black" },
      { pos: { x: 7, y: 9 }, color: "white" },
      { pos: { x: 3, y: 7 }, color: "black" },
      { pos: { x: 8, y: 6 }, color: "white" },
      { pos: { x: 7, y: 5 }, color: "black" },
      { pos: { x: 8, y: 5 }, color: "white" },
      { pos: { x: 8, y: 4 }, color: "black" },
      { pos: { x: 7, y: 4 }, color: "white" },
      { pos: { x: 6, y: 4 }, color: "black" },
      { pos: { x: 7, y: 3 }, color: "white" },
      { pos: { x: 6, y: 3 }, color: "black" },
      { pos: { x: 6, y: 6 }, color: "white" },
      { pos: { x: 6, y: 5 }, color: "black" },
      { pos: { x: 5, y: 6 }, color: "white" },
      { pos: { x: 4, y: 6 }, color: "black" },
      { pos: { x: 5, y: 8 }, color: "white" },
      { pos: { x: 4, y: 8 }, color: "black" },
      { pos: { x: 5, y: 7 }, color: "white" },
      { pos: { x: 4, y: 7 }, color: "black" },
      { pos: { x: 5, y: 5 }, color: "white" },
      { pos: { x: 5, y: 12 }, color: "black" },
      { pos: { x: 6, y: 12 }, color: "white" },
      { pos: { x: 4, y: 12 }, color: "black" },
      { pos: { x: 6, y: 13 }, color: "white" },
      { pos: { x: 12, y: 2 }, color: "black" },
      { pos: { x: 4, y: 5 }, color: "white" },
      { pos: { x: 3, y: 5 }, color: "black" },
      { pos: { x: 5, y: 4 }, color: "white" },
      { pos: { x: 5, y: 3 }, color: "black" },
      { pos: { x: 4, y: 3 }, color: "white" },
      { pos: { x: 3, y: 4 }, color: "black" },
      { pos: { x: 6, y: 2 }, color: "white" },
      { pos: { x: 5, y: 2 }, color: "black" },
      { pos: { x: 4, y: 2 }, color: "white" },
      { pos: { x: 7, y: 2 }, color: "black" },
      { pos: { x: 5, y: 1 }, color: "white" },
      { pos: { x: 3, y: 3 }, color: "black" },
      { pos: { x: 3, y: 2 }, color: "white" },
      { pos: { x: 2, y: 2 }, color: "black" },
      { pos: { x: 2, y: 1 }, color: "white" },
      { pos: { x: 1, y: 2 }, color: "black" },
      { pos: { x: 3, y: 1 }, color: "white" },
      { pos: { x: 5, y: 13 }, color: "black" },
      { pos: { x: 4, y: 10 }, color: "white" },
      { pos: { x: 4, y: 9 }, color: "black" },
      { pos: { x: 3, y: 10 }, color: "white" },
      { pos: { x: 3, y: 11 }, color: "black" },
      { pos: { x: 2, y: 11 }, color: "white" },
      { pos: { x: 2, y: 10 }, color: "black" },
      { pos: { x: 3, y: 12 }, color: "white" },
      { pos: { x: 3, y: 9 }, color: "black" },
      { pos: { x: 4, y: 13 }, color: "white" },
      { pos: { x: 3, y: 13 }, color: "black" },
      { pos: { x: 2, y: 12 }, color: "white" },
      { pos: null, color: "black" },
      { pos: { x: 2, y: 13 }, color: "white" },
      { pos: { x: 1, y: 11 }, color: "black" },
      { pos: { x: 4, y: 13 }, color: "white" },
      { pos: { x: 1, y: 12 }, color: "black" },
      { pos: { x: 1, y: 9 }, color: "white" },
      { pos: { x: 3, y: 13 }, color: "black" },
      { pos: { x: 2, y: 9 }, color: "white" },
      { pos: { x: 1, y: 13 }, color: "black" },
      { pos: { x: 2, y: 7 }, color: "white" },
      { pos: { x: 2, y: 8 }, color: "black" },
      { pos: { x: 1, y: 8 }, color: "white" },
      { pos: { x: 2, y: 6 }, color: "black" },
      { pos: { x: 3, y: 8 }, color: "white" },
      { pos: { x: 1, y: 10 }, color: "black" },
      { pos: { x: 1, y: 6 }, color: "white" },
      { pos: { x: 1, y: 5 }, color: "black" },
      { pos: { x: 1, y: 7 }, color: "white" },
      { pos: { x: 2, y: 8 }, color: "black" },
      { pos: { x: 13, y: 12 }, color: "white" },
      { pos: { x: 13, y: 11 }, color: "black" },
      { pos: { x: 1, y: 1 }, color: "white" },
      { pos: { x: 2, y: 3 }, color: "black" },
      { pos: null, color: "white" },
      { pos: { x: 7, y: 1 }, color: "black" },
      { pos: { x: 8, y: 3 }, color: "white" },
      { pos: { x: 8, y: 1 }, color: "black" },
      { pos: { x: 6, y: 1 }, color: "white" },
      { pos: null, color: "black" },
      { pos: null, color: "white" },
    ],
  });
});
